app:
  address: "127.0.0.1"
  port: 8080

db:
  mongo: 
    database1:
      address: "localhost"
      port: 27017
      name: "Erate"
      poolsize: 4
      version: "1.0.0"

jwt:
  cat1:
    secret_key: "somesupersecretkey"
    expires: '1h'

bcrypt: 
  salt_rounds: 12
